### ISSUE TITLE
Check connection file is missing

### ISSUE THREAD

**Issue by ltutar** [xebialabs-community/xlr-ansible-tower-plugin#3]
I can not find the file         <property name="scriptLocation" hidden="true" default="ansible/HttpConnectionCheck.py"/>

https://github.com/xebialabs-community/xlr-ansible-tower-plugin/blob/2f03129c4ff2adfeda33abc46e975f62dc60accb/src/main/resources/synthetic.xml#L19

**Comment by jdewinne** [comment]
Should it be `configuration/HttpConnectionCheck.py`? As that is the default value for many other plugins, and `configuration/HttpConnectionCheck.py` is part of the core XL Release installation. Can you test if that works by changing the default property?

**Comment by vlussenburg** [comment]
Implemented as such for now.
