### ISSUE TITLE
Cannot pass in limit to Extra Vars field

### ISSUE THREAD

**Issue by Steveocat** [xebialabs-community/xlr-ansible-tower-plugin#5]
Is it possible to pass in limit into the Extra Vars param along with another param. 

For example:
limt: IP_ADDRESS
cmdparms: start

**Comment by Steveocat** [comment]
Reviewed code and validated limit is not supported

**Comment by ltutar** [comment]
limit is not part of extra vars but can be submitted in addition to extra vars. Can we still have it? This limit parameter will be on the same level as inventory and credential.

`{"extra_vars":{"artifactory_petclinic_version":"pc2","artifactory_levent_version_buildnumber":"Iteration123","artifactory_levent_version_buildname":"Levent_PC2_Build_5d6d8cc6"},"limit": "UAT_servers"}
`
